### ISSUE TITLE
Get-Help Tests fail because help can't be found when developing outside the PSModulePath

### ISSUE THREAD

**Issue by jaboc83** [StartAutomating/ScriptCop#12]
Whenever the Test-Help runs it fails to find the Help for my commands 
```
Get-Help : Get-Help could not find Export-ZipFile in a help file in this session. To download updated help topics type:
"Update-Help". To get help online, search for the help topic in the TechNet library at http://go.microsoft.com/fwlink/?LinkID=107116.
At C:\Users\jmoening\workspace\ScriptCop_UB\Test-Command.ps1:114 char:32
+                 $help = $cmd | Get-Help
+                                ~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Get-Help], HelpNotFoundException
    + FullyQualifiedErrorId : HelpNotFound,Microsoft.PowerShell.Commands.GetHelpCommand
```

It appears that unless the module being analyzed lives in the module path it doesn't get loaded as the Commands get tested so it would have to be re-imported at that time, else the PSModulePath must be modified to include the working directory.

**Comment by StartAutomating** [comment]
This is by design, and pretty impossible to do otherwise.  Help has to be declared either via the module or thru inline help in order for it to be validated by ScriptCop.  Without the metadata, you can't find the help.

**Comment by jaboc83** [comment]
Yeah i'm noticing that now. I modified my calling code to temporarily add the development directory to the PSModulePath while running ScriptCop and that seems to work out
